import {
  FlaskConical,
  FileText,
  Ship,
  Settings,
  Wrench,
  BarChart3,
  Film,
  User,
  Camera,
  FolderOpen,
  TrendingUp,
  Target,
  Palette,
  Code,
  Database,
  Cloud,
  Lock,
  Mail,
  MessageSquare,
  Phone,
  Calendar,
  Clock,
  MapPin,
  Star,
  Heart,
  Home,
  Briefcase,
  BookOpen,
  GraduationCap,
  Music,
  Image,
  Video,
  FileCode,
  Globe,
  Zap,
  Rocket,
  Trophy,
  Award,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  type LucideIcon,
} from "lucide-react";

// Icon mapping for tile icons
export const ICON_MAP: Record<string, LucideIcon> = {
  "flask-conical": FlaskConical,
  "file-text": FileText,
  ship: Ship,
  settings: Settings,
  wrench: Wrench,
  "bar-chart": BarChart3,
  film: Film,
  user: User,
  camera: Camera,
  "folder-open": FolderOpen,
  "trending-up": TrendingUp,
  target: Target,
  palette: Palette,
  code: Code,
  database: Database,
  cloud: Cloud,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  phone: Phone,
  calendar: Calendar,
  clock: Clock,
  "map-pin": MapPin,
  star: Star,
  heart: Heart,
  home: Home,
  briefcase: Briefcase,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  music: Music,
  image: Image,
  video: Video,
  "file-code": FileCode,
  globe: Globe,
  zap: Zap,
  rocket: Rocket,
  trophy: Trophy,
  award: Award,
  gift: Gift,
  "shopping-cart": ShoppingCart,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
};

// Get icon component by name
export function getIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || FolderOpen;
}

// Available icons for the icon picker
export const AVAILABLE_ICONS = Object.keys(ICON_MAP);
